import {readImage,generate,designSVG,pathCSV} from './assets/engine.js';
import {lessons,knowledge,retrieve} from './assets/knowledge.js';
import {icon,primaryNav,routeIcons,activeSection} from './assets/ui.js';
import {homeMarkup,stitchArchive,palette as brandPalette} from './assets/exhibition.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset=p=>'./assets/'+p, main=$('#main');let site,patterns,products,cleanup=()=>{},epoch=0;const storeKey='lihuaji.pages.progress.v1';let progress={days:[],best:0};try{progress={...progress,...JSON.parse(localStorage.getItem(storeKey)||'{}')}}catch{}
function save(){try{localStorage.setItem(storeKey,JSON.stringify(progress))}catch{toast('浏览器未允许本地保存，本次仍可继续体验。')}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),4500)}
function modal(html){$('#modal-body').innerHTML=html;$('#modal').showModal()};$('#close-modal').innerHTML=icon('close');$('#close-modal').onclick=()=>$('#modal').close();$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#modal').close()}});
function download(name,content,type='text/plain'){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),10000)}
const title=(a,b='')=>`<div class="page-title"><div><h1>${esc(a)}</h1><p class="sub">${esc(b)}</p></div></div>`;
function image(p,src,alt){return `<img src="${esc(src)}" alt="${esc(alt)}" width="320" height="320" loading="lazy" decoding="async">`}
const patternCard=p=>`<button class="card card-image" data-pattern="${esc(p.id)}">${image(p,p.thumbnail,p.title)}<div class="card-body"><h3>${esc(p.title)}</h3><p class="sub">${esc(p.region)} · ${p.collection==='basic'?'简易':'复杂参考'}</p></div></button>`;
const productCard=p=>`<a class="card card-image link" href="#product/${encodeURIComponent(p.id)}">${image(p,asset(p.image_path),p.title)}<div class="card-body"><h3>${esc(p.title)}</h3><p class="sub">${esc(p.category)} · ${p.variants.length}种规格参考</p></div></a>`;
function bindPatterns(root=main){root.querySelectorAll('[data-pattern]').forEach(b=>b.onclick=()=>showPattern(patterns.find(x=>x.id===b.dataset.pattern)))}
function safeLink(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?esc(u.href):'#'}catch{return '#'}}
function showPattern(p){if(!p)return;modal(`<h2>${esc(p.title)}</h2><img class="image-fit" src="${esc(p.image)}" alt="${esc(p.title)}"><p>${esc(p.description||'')}</p><p>${esc(p.region)} · ${esc(p.source||'')} · ${esc(p.license||'')}</p><p>作者：${esc(p.author||'请查看原始出处')}</p><div class="row"><a class="btn" href="${safeLink(p.sourceUrl)}" target="_blank" rel="noopener noreferrer">原始出处</a><a class="btn" href="${safeLink(p.licenseUrl)}" target="_blank" rel="noopener noreferrer">使用许可</a><a class="btn primary" href="#create/${encodeURIComponent(p.id)}">以此纹样练习转稿</a></div><p class="small">本站展示图片经过尺寸压缩；使用与改编请遵守原始许可并保留署名。</p>`)}
const names={home:'首页',library:'灵感 · 祥云纹样库',create:'译绣 · 照片转稿',ar:'针法与 AR 教学',face:'文创试搭',gallery:'梨花绣馆',game:'祥云配对挑战',guide:'苏绣知识',palette:'东方色谱',profile:'我的学习记录',collaborate:'协作修改',about:'功能与隐私说明',search:'搜索绣品、针法、灵感',exhibit:'梨花新绣'};
function menu(open){
 document.body.classList.toggle('menu-open',open);
 $('#nav-scrim').hidden=!open;$('#menu').setAttribute('aria-expanded',String(open));
 $('#sidebar').inert=!open;
 if(open)$('#close-nav').focus();else if($('#sidebar').contains(document.activeElement))$('#menu').focus();
}
$('#menu').innerHTML=icon('menu');$('#close-nav').innerHTML=icon('close');
$('#site-search .search-submit').innerHTML=icon('search');$('#scan-shortcut').innerHTML=icon('scan');
$('#menu').onclick=()=>menu(!document.body.classList.contains('menu-open'));
$('#close-nav').onclick=()=>menu(false);$('#nav-scrim').onclick=()=>menu(false);
document.addEventListener('keydown',e=>{
 if(e.key==='Escape')menu(false);
 if(e.key==='Tab'&&document.body.classList.contains('menu-open')){
  const all=[...$('#sidebar').querySelectorAll('a,button,input,select')].filter(x=>!x.disabled);
  const first=all[0],last=all.at(-1);
  if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}
  else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}
 }
});
function navigate(hash){if(location.hash===hash)route();else location.hash=hash}
$('#site-search').onsubmit=e=>{e.preventDefault();navigate('#search/'+encodeURIComponent($('#global-search').value.trim()))};
function home(){
 main.innerHTML=homeMarkup(site,esc);
 main.querySelectorAll('[data-stitch]').forEach(b=>b.onclick=()=>{
  const st=stitchArchive[Number(b.dataset.stitch)];
  modal(`<article class="stitch-detail"><img src="./assets/ivory/${st.image}.webp" alt="丝线工艺概念特写"><h2>${esc(st.name)}</h2><p>${esc(st.body)}</p><p class="small">图片为针线质感概念示意。实际操作以课堂练习和专业指导为准。</p><a class="btn primary" href="#ar">进入基础针法课堂 ${icon('arrow')}</a></article>`);
 });
}
const libraryState={q:'',kind:'',region:'',page:1};
function library(){main.innerHTML=title('灵感图录 · 祥云纹样库','774份传统纹样，270份简易练习与504份复杂参考。沿着花鸟、人物与几何，走近九个文化地区。')+`<div class="filter-bar"><label>搜索题材或名称<input id="pattern-search" placeholder="花鸟、人物、几何、团花…" value="${esc(libraryState.q)}"></label><label>纹样类型<select id="pattern-kind"><option value="">全部</option><option value="basic">简易270份</option><option value="archive">复杂参考504份</option></select></label><label>文化地区<select id="pattern-region"><option value="">全部地区</option>${[...new Set(patterns.map(x=>x.region))].map(x=>`<option>${esc(x)}</option>`).join('')}</select></label></div><p id="pattern-count" role="status"></p><div id="patterns" class="grid four"></div><div id="pagination" class="row"></div>`;$('#pattern-kind').value=libraryState.kind;$('#pattern-region').value=libraryState.region;const render=()=>{const q=libraryState.q.trim().toLowerCase(),list=patterns.filter(p=>(!libraryState.kind||p.collection===libraryState.kind)&&(!libraryState.region||p.region===libraryState.region)&&(!q||[p.title,p.region,p.description,JSON.stringify(p.tags||[])].join(' ').toLowerCase().includes(q)));const pages=Math.max(1,Math.ceil(list.length/24));libraryState.page=Math.min(libraryState.page,pages);$('#pattern-count').textContent=`找到${list.length}份 · 第${libraryState.page}/${pages}页`;$('#patterns').innerHTML=list.slice((libraryState.page-1)*24,libraryState.page*24).map(patternCard).join('')||'<p>没有匹配结果，请换个关键词。</p>';$('#pagination').innerHTML=`<button id="prev" ${libraryState.page===1?'disabled':''}>上一页</button><button id="next" ${libraryState.page===pages?'disabled':''}>下一页</button>`;bindPatterns();$('#prev').onclick=()=>{libraryState.page--;render();$('#pattern-count').scrollIntoView()};$('#next').onclick=()=>{libraryState.page++;render();$('#pattern-count').scrollIntoView()}};for(const [id,key] of [['pattern-search','q'],['pattern-kind','kind'],['pattern-region','region']])$('#'+id).oninput=e=>{libraryState[key]=e.target.value;libraryState.page=1;render()};render()}
function gallery(query=''){
 main.innerHTML=title('梨花绣馆','让工艺走进日常。75件文创资料，2418种规格，慢慢看见一针一线的心意。')+`<div class="gallery-heading"><img src="./assets/ivory/garden.webp" alt="梨花园林概念场景"><p>从眼罩、丝巾到身边的小物，探索传统手艺的当代表达。<br><span class="small">图册仅作文化展示与搭配体验，不提供交易。</span></p></div><label>查找文创<input id="product-search" value="${esc(query)}" placeholder="眼罩、丝巾、手链、团扇…"></label><div id="product-categories" class="catalog-tabs" aria-label="文创分类"></div><p id="product-count" role="status"></p><div id="products" class="grid four"></div>`;
 let category='';const groups=[...new Set(products.map(p=>p.preview_group||p.category))];
 const render=()=>{const q=$('#product-search').value.trim().toLowerCase();const list=products.filter(p=>(!category||(p.preview_group||p.category)===category)&&(!q||(p.title+p.category).toLowerCase().includes(q)));$('#product-count').textContent=`共${list.length}件文创资料`;$('#products').innerHTML=list.map(productCard).join('')||'<p class="empty">暂未找到这件文创。换个名称，或看看其他分类。</p>';$('#product-categories').innerHTML=['',...groups].map(c=>`<button data-category="${esc(c)}" aria-pressed="${category===c}">${esc(c||'全部')}</button>`).join('');$('#product-categories').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.category;render()})};
 $('#product-search').oninput=render;render()
}
function product(id){const p=products.find(x=>x.id===id);if(!p)throw Error('文创条目不存在');main.innerHTML=title(p.title,'文创资料展示，不提供购买、库存承诺或真实订单。')+`<div class="split"><img class="image-fit" src="${asset(p.image_path)}" alt="${esc(p.title)}"><div class="card"><p>${esc(p.description||'')}</p><label>选择款式<select id="sku">${p.variants.map(s=>`<option value="${esc(s.id)}">${esc(s.label)}</option>`).join('')}</select></label><p id="sku-note"></p><a id="product-tryon" class="btn primary">查看此款搭配</a></div></div>`;const render=()=>{const v=p.variants.find(x=>x.id===$('#sku').value);$('#sku-note').textContent=v.note;$('#product-tryon').href=`#face/${encodeURIComponent(p.id)}~${encodeURIComponent(v.id)}`};$('#sku').onchange=render;render()}
async function create(id){let source='./assets/ivory/embroidery.webp',sourceRecord=patterns.find(x=>x.id===id);if(sourceRecord)source=sourceRecord.image;main.innerHTML=title('译绣 · 把灵感绣出来','从一张照片出发，试着安排线色与针路。图像在本机处理，工艺评估仅供小样参考。')+`<ol class="step-strip"><li><b>01</b> 选择图片</li><li><b>02</b> 调整线色</li><li><b>03</b> 下载绣稿</li></ol><div class="split create-layout"><div class="card"><img id="source-preview" class="image-fit" src="${esc(source)}" alt="当前转稿素材"><label>选择自己有权使用的图片<input id="upload" type="file" accept="image/png,image/jpeg,image/webp"></label><p class="small">照片不上传，不保存到公共仓库。刷新页面会清除当前照片。</p></div><form id="create-form" class="card"><label>作品名称<input name="title" value="${esc(sourceRecord?.title||'花间绣稿')}" maxlength="60" required></label><label>成品边长（厘米）<input name="size" type="number" value="16" min="5" max="50" required></label><label>参考线距（毫米）<input name="spacing" type="number" value="0.6" min="0.3" max="1.5" step="0.1" required></label><label>颜色数量<select name="colors"><option>4</option><option selected>6</option><option>8</option><option>12</option></select></label><label>针法<select name="stitch"><option>直线针</option><option>套针</option><option>滚针</option></select></label><label class="check"><input type="checkbox" required>我有权使用该图片，并会遵守素材的署名与使用许可。</label><button id="generate" class="primary">生成工艺参考稿</button><p id="create-status" role="status"></p></form></div><div id="result"></div>`;let loadTask=Promise.resolve();$('#upload').onchange=e=>{const file=e.target.files[0];if(!file)return;loadTask=readImage(file).then(v=>{source=v;sourceRecord=null;$('#source-preview').src=v}).catch(e=>{$('#create-status').textContent=e.message;throw e});loadTask.catch(()=>{})};const runEpoch=epoch;$('#create-form').onsubmit=async e=>{e.preventDefault();$('#generate').disabled=true;$('#create-status').textContent='正在分色与计算针路…';try{await loadTask;await new Promise(r=>setTimeout(r,30));const opt=Object.fromEntries(new FormData(e.target));opt.colors=Number(opt.colors);opt.ignoreBg=false;const d=await generate(source,opt);if(epoch!==runEpoch)return;if(sourceRecord){d.archiveSource={title:sourceRecord.title,sourceUrl:sourceRecord.sourceUrl,author:sourceRecord.author,license:sourceRecord.license,licenseUrl:sourceRecord.licenseUrl};d.svg=designSVG(d)}$('#result').innerHTML=`<h2>工艺参考稿</h2><div class="split"><div class="result-svg">${d.svg}</div><div class="card"><h3>参考评分 ${d.score}/100</h3><p>${d.paths.length}段针路 · ${d.colors.length}种数字参考色</p><p>${d.tips.map(esc).join('<br>')}</p><p>该评分不是可生产保证；先试绣小样。没有提交版权登记或上链。</p><div class="row"><button id="save-svg">下载 SVG 绣稿</button><button id="save-csv">下载针路 CSV</button></div></div></div>`;$('#save-svg').onclick=()=>download('梨花季绣稿.svg',d.svg,'image/svg+xml');$('#save-csv').onclick=()=>download('梨花季针路.csv',pathCSV(d),'text/csv');$('#create-status').textContent='已完成，结果仅在当前页面内。'}catch(err){if(epoch===runEpoch)$('#create-status').textContent=err.message}finally{if(epoch===runEpoch)$('#generate').disabled=false}}}
function shuffle(rows){const a=[...rows];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function game(){const choices=['basic','archive'].flatMap(k=>shuffle(patterns.filter(p=>p.collection===k)).slice(0,3)),deck=shuffle([...choices,...choices]);let opened=[],matched=new Set(),moves=0,locked=false,timer;main.innerHTML=title('祥云配对挑战','在翻转之间，记住一片花叶、一枚团花。六对纹样来自灵感图录，成绩留在本机。')+`<p id="game-status" role="status">已配对0/6 · 翻牌0次</p><div class="game-board">${deck.map((p,i)=>`<button class="game-card" data-card="${i}" aria-label="第${i+1}张，未翻开">梨</button>`).join('')}</div><p><button id="game-again">重新开始</button></p>`;const draw=i=>{const b=$(`[data-card="${i}"]`),p=deck[i],show=matched.has(i)||opened.includes(i);b.classList.toggle('open',show);b.classList.toggle('matched',matched.has(i));b.disabled=matched.has(i);b.setAttribute('aria-label',show?p.title:`第${i+1}张，未翻开`);b.innerHTML=show?`<img src="${esc(p.thumbnail)}" alt="${esc(p.title)}"><span>${esc(p.title)}</span>`:'梨'};main.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.card);if(locked||matched.has(i)||opened.includes(i))return;opened.push(i);draw(i);if(opened.length===2){moves++;const [a,c]=opened;if(deck[a].id===deck[c].id){matched.add(a);matched.add(c);opened=[];draw(a);draw(c)}else{locked=true;timer=setTimeout(()=>{opened=[];draw(a);draw(c);locked=false},1100)}$('#game-status').textContent=`已配对${matched.size/2}/6 · 翻牌${moves}次`;if(matched.size===12){const score=Math.max(10,100-(moves-6)*4);progress.best=Math.max(progress.best,score);save();$('#game-status').textContent=`挑战完成，${score}分！本浏览器最高分${progress.best}。`}}});$('#game-again').onclick=()=>{clearTimeout(timer);game()};cleanup=()=>clearTimeout(timer)}
function face(value=''){const [id,sku]=value.split('~');main.innerHTML=title('文创试搭','所有规格可选择；缺独立款式图时显示主图参考。目前只有银杏蓝眼罩有专用自动跟脸贴图。')+`<iframe id="face-frame" class="demo-frame" title="文创照片搭配" allow="camera" src="./face.html?v=ivory-20261005&product=${encodeURIComponent(id||'')}&sku=${encodeURIComponent(sku||'')}"></iframe>`;cleanup=()=>$('#face-frame')?.contentWindow?.postMessage({scope:'lihua-face-host',type:'stop'},location.origin)}
function ar(){main.innerHTML=title('针法档案 · 让一针看得见','先看针路，再慢慢练习。3D预览直接可用；相机识别需要同意，平面放置需设备支持。')+`<label class="check"><input id="camera-consent" type="checkbox">同意本次在设备内使用相机，不上传画面。</label><iframe id="ar-frame" class="demo-frame" title="AR针法教学" allow="camera; xr-spatial-tracking" src="./assets/ar-experience.html?v=ivory-20261005"></iframe><div class="grid">${lessons.map((l,i)=>`<article class="card"><h2>${esc(l.name)}</h2><p>${esc(l.summary)}</p><ol>${l.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p>${esc(l.tip)}</p><button data-learn="${i}">记录今日练习</button></article>`).join('')}</div>`;const send=()=>$('#ar-frame')?.contentWindow?.postMessage({scope:'lihua-ar-host',type:'consent',value:$('#camera-consent').checked},location.origin);$('#camera-consent').onchange=send;$('#ar-frame').onload=send;main.querySelectorAll('[data-learn]').forEach(b=>b.onclick=()=>{const date=new Date().toLocaleDateString('sv-SE');if(!progress.days.includes(date))progress.days.push(date);save();toast('今日练习已记在此浏览器')});cleanup=()=>$('#ar-frame')?.contentWindow?.postMessage({scope:'lihua-ar-host',type:'stop'},location.origin)}
function guide(){main.innerHTML=title('苏绣知识手册','把针法、材料与练习心得，收进随时可翻阅的小册。这里提供静态知识检索。')+'<label>查找知识<input id="knowledge-search" placeholder="针法、配色、底布…"></label><div id="knowledge-list" class="grid"></div>';const render=()=>{$('#knowledge-list').innerHTML=($('#knowledge-search').value.trim()?retrieve($('#knowledge-search').value):knowledge.slice(0,6)).map(x=>`<article class="card"><h2>${esc(x.title)}</h2><p>${esc(x.body)}</p></article>`).join('')||'<p class="empty">暂未找到这条知识，试试针法、配色或底布。</p>'};$('#knowledge-search').oninput=render;render()}
function profile(){main.innerHTML=title('我的 · 慢绣日常','不赶时间，只积攒手上的熟练。练习记录仅保存在当前浏览器，不跨设备同步。')+`<div class="metrics"><div class="metric-box"><span class="metric">${progress.days.length}</span><p>练习天数</p></div><div class="metric-box"><span class="metric">${progress.best}</span><p>配对最高分</p></div></div><div class="card"><h2>365天慢绣计划</h2><p>按自己的节奏，练习直线针、套针与滚针。</p><a class="btn primary" href="#ar">开始练习</a><p>${progress.days.slice(-14).map(esc).join('、')||'尚无练习记录'}</p><button id="export-progress">导出本机学习记录</button></div><div class="profile-links"><a class="card" href="#game">${icon('game')} 纹样配对 ${icon('arrow')}</a><a class="card" href="#palette">${icon('palette')} 东方色谱 ${icon('arrow')}</a><a class="card" href="#collaborate">${icon('users')} 协作修改 ${icon('arrow')}</a></div>`;$('#export-progress').onclick=()=>download('梨花季学习记录.json',JSON.stringify(progress,null,2),'application/json')}
function collaborate(){main.innerHTML=title('一起修改梨花季','通过公开GitHub仓库协作，提交到main分支后自动更新网站。')+`<article class="card docs-text"><h2>给朋友开放修改权限</h2><p>仓库所有者打开下方“管理合作者”，选择 Add people，输入朋友的GitHub用户名，发送邀请。朋友接受后即可编辑仓库文件。</p><div class="row"><a class="btn primary" href="${site.repository}" target="_blank" rel="noopener">打开公开仓库</a><a class="btn" href="${site.repository}/settings/access" target="_blank" rel="noopener">管理合作者（仅所有者）</a></div><h2>从哪里改内容</h2><ul><li>content/site.json：网站标题、介绍和提示。</li><li>content/patterns.json：纹样标题、地区、来源和许可。</li><li>content/products.json：文创图册与款式介绍。</li><li>app.js、style.css、pages.css：页面布局、交互与样式。</li></ul><a class="btn" href="${site.repository}/edit/main/content/site.json" target="_blank" rel="noopener">编辑首页文字</a><h2>怎样重新发布</h2><p>编辑后点击 Commit changes，提交到 main；如果创建了分支，则由所有者合并 Pull Request 到 main。仓库会自动运行 Publish GitHub Pages。等待 Actions 显示绿色成功，再刷新网站。也可在 Actions → Publish GitHub Pages → Run workflow 手动重新发布。</p><a class="btn" href="${site.repository}/actions" target="_blank" rel="noopener">查看发布进度</a><p>不需要服务器、信用卡或自购域名。公开仓库里的文件所有人都能看，请勿上传密码、客户照片或订单。</p></article>`}
function about(){main.innerHTML=title('功能与隐私说明','这是独立托管的静态文化展示与协作版，不是原后端平台的商业运营替代品。')+`<article class="card docs-text"><h2>无需作者电脑开机</h2><p>所有页面、目录和浏览器运行资源由GitHub Pages提供，不调用原电脑、临时隧道或本地端口。只要仓库与Pages服务保持可用，作者关机不影响网站托管。</p><h2>本版可以做什么</h2><p>774份纹样筛选与出处查询、75件文创图册、照片快速转工艺稿与启发式评估、SVG和针路下载、文创照片搭配、已有眼罩贴图的FaceMesh、3D针路和图像识别教学、图片配对和本机学习记录。</p><h2>本版不运行什么</h2><p>真实注册登录、会员账号、商城下单、支付、订单、定制生产、绣娘接单、上传社区、管理后台、服务器AI大模型推理与模拟链存证均未启用。没有虚构登录、支付、确权或AI成功结果。GitHub Pages不提供这些后端服务；此站也不导向商业交易。</p><h2>照片与设备权限</h2><p>照片和相机帧在浏览器内存处理，不提交服务器；保存按钮仅下载文件。离开试搭或AR页会停止相机。学习日期与游戏最高分存储在本浏览器，可用浏览器设置清除。网站托管方仍会接收正常网页访问请求。</p><h2>绢白馆藏视觉说明</h2><p>首页梨花绣框、工艺特写、丝线与园林图为AI生成的品牌概念视觉，不是馆藏实拍、商品实拍或针法研究证据。774份纹样与原有文创实拍保持原始资料来源；本次UI改造没有接通服务器AIGC、交易或登录服务。</p><h2>素材与许可</h2><p>纹样保留原始出处、作者和许可；展示图已缩小压缩，原始来源链接仍可查看。商品实拍为项目已导入文创资料。学习素材不保证可商用。第三方运行库保留各自许可，内容不因公开仓库自动变为自由授权。</p><h2>稳定地址的边界</h2><p>地址不随作者关机失效；但GitHub服务、账户状态、仓库删除和访问者网络会影响可用性，不能承诺永远在线或所有地区网络均可达。</p></article>`}

function palettePage(){
 main.innerHTML=title('东方色谱','从草木与山水中取色，把一季梨花的柔光，织进日常。')+`<div class="palette-intro"><img src="./assets/ivory/silk.webp" alt="青绿色与米白色丝线概念图"><div><h2>六色之间，留住东方。</h2><p>绢白为底，青绿为意，朱砂只作一枚小小落款。点击色卡复制颜色，或下载这套数字参考色谱。</p><p class="small">屏幕色不等于实物线色，请以真实丝线色卡和小样为准。</p><button id="download-palette">${icon('download')} 下载色谱</button></div></div><div class="palette-grid">${brandPalette.map((c,i)=>`<button class="palette-card" data-color="${i}" aria-label="复制${esc(c.name)}色值 ${c.hex}"><span class="palette-chip" style="background:${c.hex}"></span><span><strong>${esc(c.name)}</strong><code>${c.hex}</code><p>${esc(c.story)}</p></span></button>`).join('')}</div>`;
 main.querySelectorAll('[data-color]').forEach(b=>b.onclick=async()=>{
  const c=brandPalette[Number(b.dataset.color)];
  try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(c.hex);toast(c.name+' '+c.hex+' 已复制')}
  catch{modal(`<h2>${esc(c.name)}</h2><p>当前浏览器未允许自动复制，可选择下方色值复制。</p><input readonly aria-label="颜色值" value="${c.hex}" id="color-copy">`);$('#color-copy').select()}
 });
 $('#download-palette').onclick=()=>download('绢白馆藏数字色谱.txt',brandPalette.map(c=>c.name+' '+c.hex+'\n'+c.story).join('\n\n')+'\n\n数字参考色，不对应真实线号。');
}
function exhibit(){
 main.innerHTML=title('梨花新绣','循着一朵花的轮廓，重新发现苏绣的细腻。')+`<article class="exhibit-layout"><img src="./assets/ivory/embroidery.webp" alt="梨花苏绣针脚概念图"><div><span class="english">INSPIRATION ARCHIVE · No.001</span><h2>把春天，留在丝线里。</h2><p>花瓣的柔光、花蕊的细密、叶片的层次，是这次“绢白馆藏”的视觉起点。让画面少一些装饰，让一针一线成为主角。</p><p class="small">本页为品牌视觉专题，图像由AI生成，不是实际馆藏作品。真实纹样请查看灵感图录中的逐条出处与许可。</p><div class="row"><a class="btn primary" href="#library/${encodeURIComponent('花')}">浏览花卉纹样 ${icon('arrow')}</a><a class="btn" href="#create">开始译绣 ${icon('arrow')}</a></div></div></article><a class="museum-banner" href="#ar"><div><h2>从第一针开始</h2><p>先读懂丝理，再练习颜色的过渡。</p><span class="text-link">进入针法课堂 ${icon('arrow')}</span></div><img src="./assets/ivory/silk.webp" alt="丝线材质概念图"></a>`;
}
function searchPage(query=''){
 $('#global-search').value=query;
 main.innerHTML=title('寻一份灵感',query?'关于“'+query+'”的绣品、针法与纹样。':'搜索绣品、针法、灵感，从一个词开始。');
 if(!query){main.innerHTML+='<div class="row"><a class="btn" href="#search/'+encodeURIComponent('花')+'">花卉纹样</a><a class="btn" href="#search/'+encodeURIComponent('套针')+'">套针练习</a><a class="btn" href="#search/'+encodeURIComponent('眼罩')+'">苏绣眼罩</a></div>';return}
 const q=query.toLowerCase(),matchedPatterns=patterns.filter(p=>[p.title,p.region,p.description,JSON.stringify(p.tags||[])].join(' ').toLowerCase().includes(q)),matchedProducts=products.filter(p=>(p.title+p.category).toLowerCase().includes(q)),matchedKnowledge=knowledge.filter(k=>(k.title+k.tags+k.body).toLowerCase().includes(q));
 const block=(heading,items)=>'<section class="search-section"><h2>'+heading+'</h2>'+items+'</section>';
 if(matchedPatterns.length)main.innerHTML+=block('灵感图录 · '+matchedPatterns.length+'份','<div class="grid four">'+matchedPatterns.slice(0,4).map(patternCard).join('')+'</div><a class="text-link" href="#library/'+encodeURIComponent(query)+'">查看全部纹样 '+icon('arrow')+'</a>');
 if(matchedProducts.length)main.innerHTML+=block('梨花绣馆 · '+matchedProducts.length+'件','<div class="grid four">'+matchedProducts.slice(0,4).map(productCard).join('')+'</div><a class="text-link" href="#gallery/'+encodeURIComponent(query)+'">查看全部文创 '+icon('arrow')+'</a>');
 if(matchedKnowledge.length)main.innerHTML+=block('针法与知识','<div class="grid search-knowledge">'+matchedKnowledge.slice(0,3).map(k=>'<article class="card"><h3>'+esc(k.title)+'</h3><p>'+esc(k.body)+'</p><a class="text-link" href="#ar">进入基础课堂 '+icon('arrow')+'</a></article>').join('')+'</div>');
 if(!matchedPatterns.length&&!matchedProducts.length&&!matchedKnowledge.length)main.innerHTML+='<div class="empty"><p>暂未找到相关内容，试试“花”“套针”或“眼罩”。</p><a class="btn" href="#library">浏览全部纹样</a></div>';
 bindPatterns();
}
async function route(){
 cleanup();cleanup=()=>{};epoch++;menu(false);if($('#modal').open)$('#modal').close();
 let [page,id]=location.hash.slice(1).split('/');page=page||'home';
 if(page==='mall')page='gallery';if(page==='ai')page='create';if(page==='avatar')page='guide';
 if(!names[page]&&page!=='product')page='about';
 document.body.dataset.page=page;
 const section=activeSection(page);
 for(const target of ['top-nav','bottom-nav'])$('#'+target).innerHTML=primaryNav.map(([key,name,glyph])=>`<a href="#${key}" ${key===section?'class="active" aria-current="page"':''}>${target==='bottom-nav'?icon(glyph):''}<span>${name}</span></a>`).join('');
 $('#nav').innerHTML=Object.entries(names).filter(([key])=>!['search','exhibit'].includes(key)).map(([key,name])=>`<a href="#${key}" ${key===page?'class="active" aria-current="page"':''}>${icon(routeIcons[key])}<span>${esc(name)}</span></a>`).join('');
 document.title=(page==='home'?'梨花季·译绣 — 绢白馆藏':(names[page]||'文创详情')+' · 梨花季·译绣');
 try{
  const decoded=decodeURIComponent(id||'');
  if(page==='library'&&id!==undefined){libraryState.q=decoded;libraryState.page=1;libraryState.kind='';libraryState.region=''}
  await ({home,library,gallery:()=>gallery(decoded),product:()=>product(decoded),create:()=>create(decoded),game,face:()=>face(decoded),ar,guide,profile,collaborate,about,palette:palettePage,search:()=>searchPage(decoded),exhibit}[page]||about)();
  window.scrollTo(0,0);main.focus({preventScroll:true});
 }catch(e){main.innerHTML=title('页面暂时未能打开',e.message)+'<a class="btn" href="#home">回到首页</a>'}
}
try{[site,patterns,products]=await Promise.all(['site','patterns','products'].map(async x=>{const r=await fetch(`./content/${x}.json?v=ivory-20261005`);if(!r.ok)throw Error('目录加载失败，请刷新重试');return r.json()}));$('#mode-banner').textContent=site.notice;window.addEventListener('hashchange',route);await route()}catch(e){main.innerHTML=title('内容未能加载',e.message)+'<button id="reload">重新加载</button>';$('#reload').onclick=()=>location.reload()}
